---
before_install:
  - gem update --system
  - gem --version
language: ruby
notifications:
  email:
    - mike@blowmage.com
rvm:
  - 2.7.2
  - 2.7.0
  - 2.6.6
  - 2.6.0
  - 2.5.8
  - 2.5.0
  - ruby-head
gemfile:
  - gemfiles/rails-6.1.0.gemfile
