---
before_install:
  - gem update --system
  - gem --version
language: ruby
notifications:
  email:
    - mike@blowmage.com
rvm:
  - 2.6.3
  - 2.6.0
  - 2.5.5
  - 2.5.0
  - 2.4.6
  - 2.4.0
  - 2.3.8
  - 2.3.0
gemfile:
  - gemfiles/rails-5.2.3.gemfile
  - gemfiles/rails-5.2.0.gemfile
