---
before_install:
  - gem update --system
  - gem --version
language: ruby
notifications:
  email:
    - mike@blowmage.com
rvm:
  - 2.6.3
  - 2.6.0
  - 2.5.5
  - 2.5.0
  - ruby-head
gemfile:
  - gemfiles/Gemfile-rails-6.0.0.rc1
  - gemfiles/Gemfile-rails-6.0.0.beta3
  - gemfiles/Gemfile-rails-6.0.0.beta2
  - gemfiles/Gemfile-rails-6.0.0.beta1
