version: 2.1
orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  build_3-0:
    docker:
      - image: cimg/ruby:3.0
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Build CI
          command: bundle exec rake ci
  build_2-7:
    docker:
      - image: cimg/ruby:2.7
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Build CI
          command: bundle exec rake ci

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build_3-0
      - build_2-7
